name: Lint and tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test
